### ISSUE TITLE
Past Index Maps - Page Design

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#120]
https://docs.google.com/drawings/d/1ucK3iL4-FAww2X-a3F9IpjsCiow-e9n0SlE2xCElzXI/edit?usp=sharing

**Comment by niryariv** [comment]
@bnedavies where do we get the past index data from?

**Comment by woodardjoshua** [comment]
It gets generated in the matlab code but as of now we don't have it output
to csv. I can revise the matlab code to write this, but let me know the
best way to organize/structure the output please...Currently the matlab
program will write to csv the following:

(1) current premium rates (N divs rows x 1 column) for each season,
 (2) current index value (N divs rows x 1 column) based on current index
reading (for each season), and
 (3) current indennity value (N divs rows x 1 column) based on current
index reading,

and I could also have it write

 (4) historical index values (N divs #rows x M historical years # column).

I will set it to generate output for all years including the current, so
note it will grow through time. If easier, can also have it write 2 csv
with the array of historical years corresponding.

Please let me know if that works or if you want it organized some other way.

On Sun, Jun 15, 2014 at 4:36 AM, Nir Yariv notifications@github.com wrote:

> @bnedavies https://github.com/bnedavies where do we get the past index
> data from?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gizra/IBLI/issues/120#issuecomment-46110169.

## 

---

Joshua D. Woodard, PhD
Assistant Professor of Agribusiness and Finance
Zaitz Family Sesquicentennial Faculty Fellow
David R. Atkinson Center for a Sustainable Future Faculty Fellow
Dyson School of Applied Economics and Management
Cornell University
Phone: (217) 979-1251 Fax: (815) 328-2252
Email: woodardjoshua@gmail.com, jdw277@cornell.edu
Webpage: http://dyson.cornell.edu/people/profiles/woodard.php

---

Confidentiality Notice: This message, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited.  This email is considered a draft of material
that could be published at a later date, and should not be forwarded,
cited, or quoted without permission, and is subject to revision. If you are
not the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message. We do not accept legal
responsibility or otherwise for the contents of this message.

**Comment by niryariv** [comment]
Sounds good to me.

While we're at it, is it possible to add a DIV_ID (or IBLI_ID if we're switching to that) column to all CSVs? Currently we're inflecting this value from the row number, which feels too error-prone (ie if a division is dropped from the output, or IDs change etc).

**Comment by woodardjoshua** [comment]
Sure I can do this. Will roll this out to you shortly. Do you need a column
label or no?

On Mon, Jun 16, 2014 at 4:27 AM, Nir Yariv notifications@github.com wrote:

> Sounds good to me.
> 
> While we're at it, is it possible to add a DIV_ID (or IBLI_ID if we're
> switching to that) column to all CSVs? Currently we're inflecting this
> value from the row number, which feels too error-prone (ie if a division is
> dropped from the output, or IDs change etc).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gizra/IBLI/issues/120#issuecomment-46152563.

## 

---

Joshua D. Woodard, PhD
Assistant Professor of Agribusiness and Finance
Zaitz Family Sesquicentennial Faculty Fellow
David R. Atkinson Center for a Sustainable Future Faculty Fellow
Dyson School of Applied Economics and Management
Cornell University
Phone: (217) 979-1251 Fax: (815) 328-2252
Email: woodardjoshua@gmail.com, jdw277@cornell.edu
Webpage: http://dyson.cornell.edu/people/profiles/woodard.php

---

Confidentiality Notice: This message, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited.  This email is considered a draft of material
that could be published at a later date, and should not be forwarded,
cited, or quoted without permission, and is subject to revision. If you are
not the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message. We do not accept legal
responsibility or otherwise for the contents of this message.

**Comment by niryariv** [comment]
yes, column labels would be great. thanks.

**Comment by bnedavies** [comment]
@niryariv I think Josh has answered this?  Just responding to the old post directed at me...

**Comment by niryariv** [comment]
yep, this is assigned to Josh now.

**Comment by woodardjoshua** [comment]
Yes, this is in process...Andrew and APurba and I are finalizing rates and
will deliver this all at once. As soon as we get there, we will let you
know and send.

Josh

On Thu, Jun 19, 2014 at 10:02 AM, Nir Yariv notifications@github.com
wrote:

> yep, this is assigned to Josh now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gizra/IBLI/issues/120#issuecomment-46563726.

## 

---

Joshua D. Woodard, PhD
Assistant Professor of Agribusiness and Finance
Zaitz Family Sesquicentennial Faculty Fellow
David R. Atkinson Center for a Sustainable Future Faculty Fellow
Dyson School of Applied Economics and Management
Cornell University
Phone: (217) 979-1251 Fax: (815) 328-2252
Email: woodardjoshua@gmail.com, jdw277@cornell.edu
Webpage: http://dyson.cornell.edu/people/profiles/woodard.php

---

Confidentiality Notice: This message, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited.  This email is considered a draft of material
that could be published at a later date, and should not be forwarded,
cited, or quoted without permission, and is subject to revision. If you are
not the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message. We do not accept legal
responsibility or otherwise for the contents of this message.

**Comment by bnedavies** [comment]
@niryariv updated title to reflect new page listing.  Is it possible for page to show all past (final) index maps back to 2005?  Maybe the user can scroll over the same map from the homepage and a pop-up box could allow them to pick the Final Index Reading by year (2014, 2013, 2012, etc.) and by month (March or October). 

![final index map](https://cloud.githubusercontent.com/assets/6724026/3480584/eee41b70-0362-11e4-8d48-1b9b9a09c00c.png)

**Comment by niryariv** [comment]
@bnedavies how about this: when a user hovers a unit in the homepage map, we'll have a box in the bottom left corner showing the past indexes for that area? 

we could replace the current box which won't be needed since we have the popup on each unit:

![screen shot 2014-07-06 at 12 04 42 pm](https://cloud.githubusercontent.com/assets/1771/3488531/c6088fa2-04ec-11e4-8de9-2603455d1f9f.png)

**Comment by bnedavies** [comment]
@niryariv that sounds good, but I think we will need one page dedicated to these maps as well, as we had planned originally.  These are how we build the community's trust in the product and communicate the payout status to donors, the insurer, etc.  We will also need to be able to download a PDF of the map as above...or some other ormat to record the readings and distribute to the community...

**Comment by niryariv** [comment]
implemented as http://dev-ibli.gotpantheon.com/pim
