### ISSUE TITLE
Toolchain step 3: Optimize

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#13]
Once #11 is done and we've checked #12, @vrieling can start optimizing the scripts as he sees fit. This is less critical initially since the process only runs every 10 days, so total runtime < 9 days is manageable for now..

**Comment by mbrv** [comment]
Hi !

While going through the code i saw some possible optimization suggestions :
1. currently the stacking of the individual NDVI's into one large multi-band image is done by reading in this order : line - band - sample .
- this way of reading the data is good and nessecery for : calculating the diagnostics image which needs all the temporal data (band) of a pixel together (for percentile calculations).
- this was of reading the data is bad in terms of running time : we need to "open" and "close" a file : LINES X BAND times . a much more appropriate way in terms of running time optimizations would be reading and writing the file in this order : line - sample - band . in this way we read and write only :BAND times.

my suggestion is : 

```
  - since the diagnostic file mostly stays unmodified : we can write a seperate code which would calculate him when nessecery using the unefficienct but nessecery for its calculation by reading : line - band - sample.
  - re-write the code (almost most of it) so that it :
    a. wont be reading/writing : line-band-sample but rather line-sample-band.
    b. it will not calculate the diagnostics image but will use a pre-calculated diagnostics image.

when reading line-sample-band a very noticable improvment in running time should be seen.
```
1. currently the code calculates the mean and variance every time (and also the diagnostics) - i think it is safe to use the same mean and variance file which was calculated for the first 10 years safely because it should change that much. if this option would be implemented in the code it should save some additional running time ( although if we'll change the reading to line-sample-band ordered i think this improvment will be lighter and less significant).

**Comment by niryariv** [comment]
@vrieling what do you think?

**Comment by vrieling** [comment]
Yesterday and today out of office. I do not clearly see how the proposed change may speed up things, but feel free to test!

I think however that main priority for IBLI now is to have a flexible way to define aggregation areas (spatial units). Not sure if there is need to concentrate on speeding up now but if you see good options,please try and check if output is stable. I do not envisage reprogramming for speed myself.

Sent from Samsung Mobile

-------- Original message --------
