### ISSUE TITLE
provide final matlab code 

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#175]

**Comment by niryariv** [comment]
@apurbashee how is this going? any ETA for the new code?

**Comment by woodardjoshua** [comment]
I believe I sent everything that Apurba needed a few weeks back, but let me
know if there is something else that is needed.

On Thu, Aug 7, 2014 at 10:50 AM, Nir Yariv notifications@github.com wrote:

> @apurbashee https://github.com/apurbashee how is this going? any ETA
> for the new code?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gizra/IBLI/issues/175#issuecomment-51482242.

## 

---

Joshua D. Woodard, PhD
Assistant Professor of Agribusiness and Finance
Zaitz Family Sesquicentennial Faculty Fellow
David R. Atkinson Center for a Sustainable Future Faculty Fellow
Dyson School of Applied Economics and Management
Cornell University
Phone: (217) 979-1251 Fax: (815) 328-2252
Email: woodardjoshua@gmail.com, jdw277@cornell.edu
Webpage: http://dyson.cornell.edu/people/profiles/woodard.php

---

Confidentiality Notice: This message, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited.  This email is considered a draft of material
that could be published at a later date, and should not be forwarded,
cited, or quoted without permission, and is subject to revision. If you are
not the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message. We do not accept legal
responsibility or otherwise for the contents of this message.

**Comment by apurbashee** [comment]
Hi Nir,
I have just sent you the updated matlab folder and premiums with email
attachments.
Thanks
Apurba
