### ISSUE TITLE
Index values

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#26]
@apurbashee could you list the various index levels for the map (eg: `0.1-0.299 high risk red`) and which CSV file in https://github.com/Gizra/IBLI/tree/master/IBLIMatlab we should be reading the indexes from?

**Comment by apurbashee** [comment]
@niryariv The Indexes can be read from “SRSDfinalIndex.csv” and “LRLDfinalIndex.csv”. And for index updating we will get them after putting the Czndvi for the ongoing season as described by @woodardjoshua in “Readme.txt”..
The color coding of the index for IBLI Kenya are the following
Green: 0 - 0.06
Yellow: 0.06 - 0.08
Orange: 0.08 – 0.1
Red: 0.1 – 0.15
Black: 0.15 – 1.0
The color coding of Ethiopian index are different, they are based on percentile calculation
Green: Above 65 percentile 
Yellow: 45 percentile – 65 percentile
Orange: 30 percentile – 45 percentile
Red: 15 percentile – 30 percentile
Black: Less than 15 percentile
I will send you two example files for the index legend for both Kenya and Ethiopia..

**Comment by niryariv** [comment]
@apurbashee - so, this means that we need to refer to LRLD or SRSD depending on which season we're displaying data for?

**Comment by niryariv** [comment]
@apurbashee can you explain how we should use the SRSD/LRLD indexes? Which do we show to the user when?

**Comment by woodardjoshua** [comment]
After the respective insured season is over (LRLD or SRSD) we publish the
realized index value for that season based on the czNDVI outcome.

For example, the LRLD season runs from March 1-Sept 30th, so right now we
are in the LRLD season for 2014. When final NDVI data become available for
the LRLD period for 2014, we download and process it (which occurs sometime
in October 2014) and then calculate the index values as defined by the
contract using the matlab code. We then post the realized index values and
indemnities for the LRLD 2014 season which result from those realized NDVI
outcomes.

On Tue, Apr 29, 2014 at 3:14 AM, Nir Yariv notifications@github.com wrote:

> @apurbashee https://github.com/apurbashee can you explain how we should
> use the SRSD/LRLD indexes? Which do we show to the user when?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Gizra/IBLI/issues/26#issuecomment-41647507
> .

## 

---

Joshua D. Woodard, PhD
Assistant Professor of Agribusiness and Finance
Zaitz Family Sesquicentenntial Faculty Fellow
David R. Atkinson Center for a Sustainable Future Faculty Fellow
Dyson School of Applied Economics and Management
Cornell University
Phone: (217) 979-1251 Fax: (815) 328-2252
Email: woodardjoshua@gmail.com, jdw277@cornell.edu
Webpage: http://dyson.cornell.edu/people/profiles/woodard.php

---

Confidentiality Notice: This message, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited.  This email is considered a draft of material
that could be published at a later date, and should not be forwarded,
cited, or quoted without permission, and is subject to revision. If you are
not the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message. We do not accept legal
responsibility or otherwise for the contents of this message.

**Comment by niryariv** [comment]
Thanks @woodardjoshua. So to create the website mortality indexes map, we'll need to determine current season (SRSD/LRLD) and read the values from, say, [LRLDfinalIndex.csv](https://github.com/Gizra/IBLI/blob/master/dataProcessing/IBLIMatlab/LRLDfinalIndex.csv). Correct?

**Comment by apurbashee** [comment]
@niryariv , regarding how we should use SRSD/LRLD indexes we will use them in two ways.
1) Index update: as Josh mentioned, this will be for an ongoing insured season. Since we have eMODIS available every 10 days we should have index update every 10 days as well. Based on the realized Czndvi we will get index values as coded in MatLab. Then, these indexes will be used to create the color maps using the color coding mentioned above. We usually provide these maps to the insured community so that they become aware of the status of the index within a season.
2)  Historical index experience: The csv files “SRSDfinalIndex” and “LRLDfinalIndex” have the historical index values. Using these files we should be able to produce two things on the website. First, we should create line graph for every division (multi-series linegraph) in a county. These graphs are important to see how the index performance has been in a specific county. This is what our partners, insurance companies, and policy makers are interested in. Second, similar to 1) we have to create the color maps for these historical indexes. 
I have shown you how these graphs and maps look like.. but can discuss further.

**Comment by niryariv** [comment]
> Then, these indexes will be used to create the color maps using the color coding mentioned above

What's the name of the file we should read indexes from when generating the map? Is it LRLDfinalIndex.csv and SRSDfinalIndex.csv or do they need to go through more processing before being used?

**Comment by woodardjoshua** [comment]
These are the processed values.
