### ISSUE TITLE
Automating data processing chain

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#39]
The final step in automating the data processing code would be to allow all the different parts to work together. There are 3 parts so far:
1. Fetch new NDVI data from usgs.gov 
2. Process data via IDL toolchain
3. Process output via Matlab.

(Current 1 & 2 are done by the same code - we may want to separate them in order to have a more loosely coupled process chain).

I suggest we add code to the IDL and Matlab components which does the following:
1. Check component's input file and output file last modify date.
2. If the input file is older than the output file, assume no new data and exit.
3. If input file is more recent than output, we assume it contains new data, execute data processing and create new output file.

This should allow us to call the tasks from cron, every n hours, without actually having to run them if there's no new data or keep some system for tracking new data.

@alanorth @woodardjoshua @mbrv @amitaibu @bricel - thoughts?

**Comment by mbrv** [comment]
Regarding seperating the USGS Repository fetching and the tool cahin it self -  no problem it can be done easily. should i write a seperate "getRepository" function ? 

the IDL code already has something similar to what you mentioned so that it runs only if there is new data from USGS (as suggested in https://github.com/Gizra/IBLI/wiki/IDL-Toolchain : the code makes sure we update only on the 4th , 14th and 25th of each month - if its any other day it exits).

so - assuming that n<24*9 hours : you can run cron every n hours and be certain the repository is up to date without having to run the entire process every time.
- \- Sorry Accidently Closed this issue ealier - reopened . . .

**Comment by niryariv** [comment]
@mbrv can you link (on github) to the part of the code that handles the DL? if we pull it out of the main code, perhaps we'll rewrite in some Python or something (or just wget on shell if it's really simple code)

**Comment by woodardjoshua** [comment]
This should work in matlab as well. If you import a csv with date
associated with IDL files, and compare it with previous (which you can
export and save from previous run) it should be easy to write an if/exit
statement to compare.

Here are the relevant date and time functions you would need

_http://www.mathworks.com/help/matlab/date-and-time-operations.html
http://www.mathworks.com/help/matlab/date-and-time-operations.html_

_I know you all converted this code to linux somehow, and so not sure what
the current version is that you are working with._

_Josh_

On Sun, May 11, 2014 at 10:57 AM, mbrv notifications@github.com wrote:

> Regarding seperating the USGS Repository fetching and the tool cahin it
> self - no problem it can be done easily. should i write a seperate
> "getRepository" function ?
> 
> the IDL code already has something similar to what you mentioned so that
> it runs only if there is new data from USGS (as suggested in
> https://github.com/Gizra/IBLI/wiki/IDL-Toolchain : the code makes sure we
> update only on the 4th , 14th and 25th of each month - if its any other day
> it exits).
> 
> so - assuming that n<24*9 hours : you can run cron every n hours and be
> certain the repository is up to date without having to run the entire
> process every time.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Gizra/IBLI/issues/39#issuecomment-42772768
> .

## 

---

Joshua D. Woodard, PhD
Assistant Professor of Agribusiness and Finance
Zaitz Family Sesquicentennial Faculty Fellow
David R. Atkinson Center for a Sustainable Future Faculty Fellow
Dyson School of Applied Economics and Management
Cornell University
Phone: (217) 979-1251 Fax: (815) 328-2252
Email: woodardjoshua@gmail.com, jdw277@cornell.edu
Webpage: http://dyson.cornell.edu/people/profiles/woodard.php

---

Confidentiality Notice: This message, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited.  This email is considered a draft of material
that could be published at a later date, and should not be forwarded,
cited, or quoted without permission, and is subject to revision. If you are
not the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message. We do not accept legal
responsibility or otherwise for the contents of this message.

**Comment by mbrv** [comment]
@niryariv   - Sure , just : what does DL means ?

**Comment by woodardjoshua** [comment]
Apologies...meant IDL...the NDVI files.

On Tue, May 13, 2014 at 1:44 AM, mbrv notifications@github.com wrote:

> @niryariv https://github.com/niryariv - Sure , just : what does DL
> means ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Gizra/IBLI/issues/39#issuecomment-42919260
> .

## 

---

Joshua D. Woodard, PhD
Assistant Professor of Agribusiness and Finance
Zaitz Family Sesquicentennial Faculty Fellow
David R. Atkinson Center for a Sustainable Future Faculty Fellow
Dyson School of Applied Economics and Management
Cornell University
Phone: (217) 979-1251 Fax: (815) 328-2252
Email: woodardjoshua@gmail.com, jdw277@cornell.edu
Webpage: http://dyson.cornell.edu/people/profiles/woodard.php

---

Confidentiality Notice: This message, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited.  This email is considered a draft of material
that could be published at a later date, and should not be forwarded,
cited, or quoted without permission, and is subject to revision. If you are
not the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message. We do not accept legal
responsibility or otherwise for the contents of this message.

**Comment by mbrv** [comment]
Sure . The part of the code that handles the NDVI Repository is highlighted here :

https://github.com/Gizra/IBLI/blob/master/dataProcessing/eMODIS_SHELL/emodisshell.pro#L175-291

*note that " ; " in IDL means comment
